### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by decoded-cipher** [iSaulX/DTMA-YouTube#12]
![image](https://github.com/iSaulX/DTMA-YouTube/assets/44474792/97775dde-1c9d-4c94-9268-689807553895)

@iSaulX I've tried the same. But, this approach doesn't seem to work

**Comment by iSaulX** [comment]
Hi! This extensions only work with this type of PopUp 
![image](https://github.com/iSaulX/DTMA-YouTube/assets/115506411/db1d5ee7-6a5d-462e-abb0-6ca07b859029)
This happen before you get restricted to play videos. I keep working to found  a way to avoid this.

Tip: (If you have another google account. switch, play one video and then come back to your original account) :P
